#spring.application.name=gym_management
#
## MySQL Config
#spring.datasource.url=jdbc:mysql://localhost:3306/gym_management
#spring.datasource.username=root
#spring.datasource.password=Mysql
#
## JPA Config
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
## Server Port
#server.port=8080

spring.application.name=gym_management

spring.datasource.url=jdbc:mysql://roundhouse.proxy.rlwy.net:24526/railway
spring.datasource.username=root
spring.datasource.password=GVEkclCuxVPwDSTFceQkQTuwxCrAMlWG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}